//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballMatchOrganizer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.PlayerOnMatches = new HashSet<PlayerOnMatch>();
        }
    
        public int Id { get; set; }
        public System.DateTime MatchTime { get; set; }
        public string MatchPlace { get; set; }
        public string Status { get; set; }
        public int HostTeamId { get; set; }
        public short HostTeamResult { get; set; }
        public int GuestTeamId { get; set; }
        public short GuestTeamResult { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerOnMatch> PlayerOnMatches { get; set; }
    }
}
